import Head from "next/head";
import LoadSpinner from "~/components/LoadSpinner";

import { api } from "~/utils/api";
// import type { RouterOutputs } from "~/utils/api";

export default function ProfilePage() {
  const { data, isLoading: profileIsLoading } = api.profile.getUserByUsername.useQuery({
    username: "anjasfedo",
  });

  if (profileIsLoading) return <LoadSpinner />;

  if (!data) return <div>Something wrong</div>;

  console.log(data);

  return (
    <>
      <Head>
        <title>Profile Page</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen justify-center">
        <div>Profile Page</div>
      </main>
    </>
  );
}
