import Head from "next/head";

import { api } from "~/utils/api";
// import type { RouterOutputs } from "~/utils/api";

import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Layout from "~/components/Layout";

export default function PostPage() {
  const { isLoaded: userIsLoaded, isSignedIn } = useUser();

  // Start fetch (use the cache)
  api.post.getAll.useQuery();

  // Return empty div if user not loaded
  if (!userIsLoaded) return <div />;

  return (
    <>
      <Head>
        <title>Post Page</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        Post Page
      </Layout>
    </>
  );
}
